CREATE TABLE L_TRAB(
    NOMBRE varchar(255) NOT NULL PRIMARY KEY,
    EDAD INT,
    SUELDO INT
);
INSERT INTO L_TRAB
VALUES (
'Marcos Pérez', 35, 5000
);
SELECT * FROM L_TRAB WHERE NOMBRE='Marcos Pérez';
